POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
    "name": "Test User",
    "username": "testuser123",
    "email": "testuser123@example.com",
    "password": "secret123"
}